### ISSUE TITLE
PHP min version

### ISSUE THREAD

**Issue by rafark** [Mistralys/subsetsum#1]
Thank you for writing this! It works like an absolute charm.

Just as an FYI, it requires PHP 7.1 (which isn't stated in the docs or in packagist). And for everyone interested, you can make it PHP 7.0 compatible by removing the nullable return types (just 2 instances: ?array).

PS. I'm your first star.

**Comment by Mistralys** [comment]
Thanks for the bug report, @rafark! I also saw what I suspect was your comment on stackoverflow. I created an issue for it (#2 ), and will have a look :)
